export const home: string;
export const heroimage: string;
export const heroText: string;
export const containerText: string;
export const elem: string;
export const button: string;
export const container: string;
export const filePreview: string;
export const loading: string;
